parameters:
#    wanasni_trajet.example.class: Wanasni\TrajetBundle\Example

services:
#    wanasni_trajet.example:
#        class: %wanasni_trajet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
